### ISSUE TITLE
can't create indexes from GORM mapping

### ISSUE THREAD

**Issue by benlucchesi** [grails-plugins/grails-database-migration#41] opened 2015-11-09 23:57 UTC
Hi,

I'm trying to create indexes from a domain class mapping and I'm getting exceptions thrown.

here's the mapping:
```
class CompanyCustomer {

    static constraints = {
    }

    static mapping = {
      customer column: 'customer_id', index: 'customer_idx'
    }

    Customer customer
    Company  company
    Date dateCreated
    Date dateDeactivated
}
```
here's the command:
$grails dbm-gorm-diff --debug
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:findMainClass
:dbmGormDiff
objc[10755]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

Configuring Spring Security Core ...
... finished configuring Spring Security Core

Command execution error: liquibase.command.CommandExecutionException: java.util.ConcurrentModificationException
:dbmGormDiff FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dbmGormDiff'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 23.878 secs
| Error Error occurred running Grails CLI: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1 (Use --stacktrace to see the full trace)

Any ideas what's going on? 
Let me know if you want the full stack trace.

**Comment by robertoschwald** [comment] 2016-05-31 12:14
Duplicate of #47 ?

Try 2.0.0.RC4

**Comment by Schlogen** [comment] 2016-07-01 19:17
@benlucchesi Can you try RC4 to see if that resolves your problem?

**Comment by Schlogen** [comment] 2016-07-18 15:37
Closing this as I believe RC4 will resolve the issue. Reopen if that is not the case

**Closed by Schlogen** 2016-07-18 15:37 UTC
Labels: Awaiting Feedback
