### ISSUE TITLE
liquibase NPE 'Name is null' with Grails 3.0.17 and v2.0.0

### ISSUE THREAD

**Issue by j4y** [grails-plugins/grails-database-migration#106] opened 2016-12-08 18:04 UTC
We are currently using version `2.0.0.RC4` and would like to upgrade to `2.0.0`, but receive an error running the app when we simply change the version.  It looks like it is having trouble parsing the change log file.

```
ERROR grails.boot.GrailsApp - Application startup failed
liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: java.lang.NullPointerException: Name is null
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:27) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:229) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:202) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:192) ~[liquibase-core-3.5.3.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:431) ~[liquibase-core-3.5.3.jar:na]
	at org.grails.plugins.databasemigration.liquibase.GrailsLiquibase.performUpdate(GrailsLiquibase.groovy:80) ~[database-migration-2.0.0.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:388) ~[liquibase-core-3.5.3.jar:na]
	at org.springframework.beans.factory.InitializingBean$afterPropertiesSet.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) [groovy-2.4.5.jar:2.4.5]
	at org.grails.plugins.databasemigration.DatabaseMigrationGrailsPlugin$_doWithApplicationContext_closure2$_closure5.doCall(DatabaseMigrationGrailsPlugin.groovy:87) ~[database-migration-2.0.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426) ~[springloaded-1.2.6.RELEASE.jar:1.2.6.RELEASE]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-2.4.5.jar:2.4.5]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294) ~[groovy-2.4.5.jar:2.4.5]
```

**Comment by jameskleeh** [comment] 2016-12-08 18:15
Please provide an example application that demonstrates the issue

**Comment by j4y** [comment] 2016-12-08 21:08
The application I'm working on is not open source so I will have to come up with an example.  Any ideas where to look?  It's expecting a 'Name' parsing the changelog.

Also did anything significant change between `2.0.0RC4` and `2.0.0`?  RC4 works fine for us.

**Comment by jameskleeh** [comment] 2016-12-08 21:10
The version of liquibase was updated. That is most likely the cause

**Comment by jameskleeh** [comment] 2017-01-18 15:24
Closing due to no example provided.

**Closed by jameskleeh** 2017-01-18 15:24 UTC
Labels: 2.x, Awaiting Feedback
