### ISSUE TITLE
dbm-update - BootStrap.groovy should not run before migration

### ISSUE THREAD

**Issue by snimavat** [grails-plugins/grails-database-migration#78] opened 2016-06-12 13:40 UTC
So, i am using grails 3.1.6

- Created a fresh changelog.groovy from Domains using dbm-generate-gorm-changelog
- Datasource is setup, all good, dbUpdate: none
- A blank my sql db is created
- My BootStrap.groovy uses Domain classes, and creates default users if does not exist.
- I run dbm-update - but it fails - because BootStrap.groovy is executed before migration, so, the tables still does not exist in database.. and it fails.

However, if i have ```grails.plugin.databasemigration.updateOnStart = true``` -and i do run-app the migration will run before BootStrap, and database is created properly.

But for test environments, grails.plugin.databasemigration.updateOnStart = true doesnt work somehow, and i have to run dbm-update to create the initial database.. but there's no way for migration to run, as it would always fail on BootStrap.

This was not the case with older versions of grails. I think it used to work fine.

**Comment by snimavat** [comment] 2016-06-27 05:25
@bobbywarner @jeffbrown is this an issue ? or you think this is a valid behaviour ?

**Comment by zyro23** [comment] 2016-06-27 11:16
i think the issue is that currently, bootstrap is run for `ApplicationCommand`s.
while the behavior may be valid in general, for the case of database-migration i agree that it is completely undesired.
my _really_ ugly workaround in bootstrap to get it working somehow looks like this:
```groovy
def init = { servletContext ->
    if (launchedByApplicationCommand) return
}

// FIXME: currently, BootStrap is always executed for ApplicationCommands which is undesired for dbm commands
private boolean isLaunchedByApplicationCommand() {
    def mainClassName = Thread.currentThread().stackTrace.find { it.methodName == "main" }?.className
    return mainClassName == "grails.ui.command.GrailsApplicationContextCommandRunner"
}
```

**Comment by Schlogen** [comment] 2016-07-02 15:10
Duplicate of https://github.com/grails-plugins/grails-database-migration/issues/42

**Closed by Schlogen** 2016-07-02 15:10 UTC
