### ISSUE TITLE
Excessive re-creation of all Foreign Key, index and unique constraints, plus primary key sequence default values in plugin 2.x with postgres 9.5.x

### ISSUE THREAD

**Issue by edwardotis** [grails-plugins/grails-database-migration#100] opened 2016-11-21 16:33 UTC
I recently migrated from grails 2.5 to grails 3.1. My datamigration changelogs on the existing database are filled with recreations of all my pre-existing Foreign Key, index and unique constraints, plus postgres primary key sequences. 

I had a few repeated, re-recreations in each diff in the 1.x plugin around booleans, but they were manageable to hand delete each time. With the 2.x plugin,  I get over 600 lines of re-creations on each diff, interspersed with the real changes. It makes it very difficult to use this version of the plugin to manage my database.

Furthermore, I tested to see if this was purely a problem of moving from from database-migration plugin 1.x to 2.x. I backed up my old data, and let the 2.0.0 data-migration plugin take my existing changelogs to recreate my database schema from scratch. The resulting db schema looks correct for all tables, foreign keys, uniques, indexes, sequences, etc. (great!)

Then, I ran dbm-gorm-diff immediately without making any other changes to my code base.
It spits out the same 600+ lines recreating all my Foreign Key, index and unique constraints, plus postgres primary key sequences. 

Then, I tried dbm-update with these 600 lines to see if they could be applied and not be recreated in the future. However, running these changes raises the following exception after 100 lines:

ERROR liquibase - changelog.groovy: changelog_049_recreate_test.groovy::1479746974168-25::myuser (generated): Change Set changelog_049_recreate_test.groovy::1479746974168-25::myuser (generated) failed.  Error: ERROR: constraint "FK_b7lh7f3gvmok8q8f8a5i09m05" of relation "my_table" does not exist [Failed SQL: ALTER TABLE public.my_table DROP CONSTRAINT "FK_b7lh7f3gvmok8q8f8a5i09m05"]
Command execution error: Migration failed for change set changelog_049_recreate_test.groovy::1479746974168-25::myuser (generated):
     Reason: liquibase.exception.DatabaseException: ERROR: constraint "FK_b7lh7f3gvmok8q8f8a5i09m05" of relation "my_table" does not exist [Failed SQL: ALTER TABLE public.my_table DROP CONSTRAINT "FK_b7lh7f3gvmok8q8f8a5i09m05"]

I investigated in my newly created schema, and the constraint in question was named in the db: 
FK_6c1rtv3qh3phfrobas8tdrwxh

And the plugin diff is trying to use this in the changeset: 
FK_b7lh7f3gvmok8q8f8a5i09m05

Hence the error.

What's even more confusing, is that the plugin was able to generate the correct fk constraint name in 12 changesets leading up this one.

So, I think this may represent 2 distinct bugs in the 2.x.x database migration plugin

Ideas?

Environment Information:

Old: 
grails 2.5.5
liquibase database-migration:1.4.1
org.postgresql:postgresql:9.4.1207
postgresql-extensions:4.6.1
hibernate4:4.3.10
org.jadira.usertype:usertype.core:4.0.0.GA
Postgres 9.5
Java 8
Ubuntu 14.04LTS

New:
grails 3.1.14
runtime 'org.grails.plugins:database-migration:2.0.0'
compile 'org.liquibase:liquibase-core:3.5.3
org.postgresql:postgresql:9.4.1212
postgresql-extensions:4.6.8
compile "org.grails.plugins:hibernate4:5.0.12"
compile "org.hibernate:hibernate-core:4.3.11.Final"
compile "org.hibernate:hibernate-ehcache:4.3.11.Final", {
     exclude module: 'ehcache-core'
 }
compile("org.jadira.usertype:usertype.core:4.0.0.GA") {
    exclude group: 'org.hibernate', module: 'hibernate-entitymanager'
}
    //BEGIN spring-security-ui depends on explicit hibernate4:5.0.x
    compile 'org.grails:grails-datastore-core:5.0.12.RELEASE'
    compile 'org.grails:grails-datastore-gorm-support:5.0.12.RELEASE'
    compile 'org.grails:grails-datastore-gorm:5.0.12.RELEASE'
    compile 'org.grails:grails-datastore-simple:5.0.12.RELEASE'
    compile 'org.grails:grails-datastore-gorm-hibernate4:5.0.12.RELEASE'
    compile 'org.grails:grails-datastore-gorm-hibernate-core:5.0.12.RELEASE'
Postgres 9.5
Java 8
Ubuntu 14.04LTS

**Comment by jameskleeh** [comment] 2016-11-21 16:38
The 1.x versions of this plugin is in no longer being maintained. Most likely your problems are with liquibase which would require you to upgrade to Grails 3 and DBM 2.x or 3.x

**Comment by edwardotis** [comment] 2016-11-21 17:17
@jameskleeh Sorry, a keyboard short cut key published my post while I was still editing. Please see my updated issue report.

**Comment by jameskleeh** [comment] 2016-11-21 17:23
Part of this is a duplicate of https://github.com/grails-plugins/grails-database-migration/issues/95

Essentially you should raise issues with `liquibase-hibernate`. The plugin is working as designed, it is the liquibase side that is not working as you would expect.

My advice is to create your changesets manually until the issues are resolved

**Comment by edwardotis** [comment] 2016-11-21 18:32
ok, thanks

**Comment by edwardotis** [comment] 2016-11-22 18:49
Looks like they were able to fix the problem for the hibernate5 version of liquibase-hibernate:

https://github.com/liquibase/liquibase-hibernate/issues/129

**Comment by edwardotis** [comment] 2016-12-02 16:14
@jameskleeh given that the Grails 2.x version of this plugin currently works fine with hibernate4. Is it possible to roll back to a previous, correctly functioning, liquibase-hibernate dependency in the Grails 3.x database migration plugin?

**Comment by jameskleeh** [comment] 2016-12-02 16:17
@edwardotis Previous versions had other issues that were resolved, so I don't see the benefit in doing so

**Comment by edwardotis** [comment] 2016-12-02 16:19
@jameskleeh ok, fair point

**Comment by edwardotis** [comment] 2016-12-05 23:36
I added a pull request to liquibase-hibernate

https://github.com/liquibase/liquibase-hibernate/pull/138

**Comment by bobbywarner** [comment] 2020-07-14 15:37
Fixed by https://github.com/grails-plugins/grails-database-migration/pull/175

**Closed by bobbywarner** 2020-07-14 15:37 UTC
Labels: status: awaiting third-party, version: 2.x
