### ISSUE TITLE
dbm-gorm-diff creates repeatedly defaultValueBoolean

### ISSUE THREAD

**Issue by markoschnecke** [grails-plugins/grails-database-migration#69] opened 2016-04-28 16:23 UTC
dbm-gorm-diff creates repeatedly changesets for default values of boolean variables regardless of whether that change was already executed.
Example Domain:

```
package minimal_liquibase
class ExampleDomain {
    Boolean exampleBoolean

    static  constraints = {
        exampleBoolean nullable: false
    }
    static mapping = {
        exampleBoolean defaultValue: true, index:'test_idx'
    }
}
```
With only that I executed `dbm-generate-gorm-changelog changelog.groovy` with the following result:

```
databaseChangeLog = {

    changeSet(author: "marko (generated)", id: "1461858302502-1") {
        createTable(tableName: "example_domain") {
            column(autoIncrement: "true", name: "id", type: "BIGINT") {
                constraints(primaryKey: "true", primaryKeyName: "example_domainPK")
            }

            column(name: "version", type: "BIGINT") {
                constraints(nullable: "false")
            }

            column(defaultValueBoolean: "true", name: "example_boolean", type: "BOOLEAN") {
                constraints(nullable: "false")
            }
        }
    }
}
```
To apply that ChangeLog I started the app once `run-app` and then created a diff with `dbm-gorm-diff diff.groovy`. The diff includes the defaultValueBoolean again:
```
databaseChangeLog = {

    changeSet(author: "marko (generated)", id: "1461858372439-1") {
        addDefaultValue(columnDataType: "boolean", columnName: "example_boolean", defaultValueBoolean: "true", tableName: "example_domain")
    }
}
```
The default value for the column is set correctly in the database, though.
Also, it is interesting that no Index is created, neither in the original changelog nor in the diff-changelog.

I used:
- grails 3.1.5
- database-migration:2.0.0.RC4
- mysql-connector-java:5.1.26
- MySQL 5.7.12-0ubuntu1
- hibernate4:5.0.4

I also attached the example grails project as a zip file. Obviously you have to adjust the dataSource settings in the application.yml but besides that u should be able to run it directly.

[minimal_liquibase.zip](https://github.com/grails-plugins/grails-database-migration/files/240941/minimal_liquibase.zip)

**Comment by burtbeckwith** [comment] 2016-04-28 16:31
I just noticed the same today in a project after updating to RC4 from RC1.

**Comment by davidbairdala** [comment] 2016-05-02 06:02
I have this issue also. The problem also manifests with columns mapped explicity to 'text' as well.
I'm using grails 2.5.4, Postgres 9.4. My workflow now is to run dbm-gorm-diff to a new file, manually peruse the file and copy out the entries that I know I have changed, skipping over every boolean and text column, and pasting those changelogs to my master changelog.groovy.

**Comment by nilskuhn** [comment] 2016-05-18 10:01
Same error for me :(
Would be great if somebody would fix this!

**Comment by Schlogen** [comment] 2016-07-01 21:46
@burtbeckwith The reason this is happening is because the value in MySQL for example is "1" and the value in GORM is "true". I'm not sure the best way to solve this, but that is the cause.

**Comment by Schlogen** [comment] 2016-07-15 13:50
To the best of my ability, I believe this is a liquibase issue. I filed a ticket in their Jira:

https://liquibase.jira.com/browse/CORE-2831

**Comment by jameskleeh** [comment] 2016-10-27 19:04
@markoschnecke Looks like that bug was fixed in liquibase 3.5.2. That version of liquibase is in version `3.0.0.BUILD-SNAPSHOT` of the plugin. Can you give it a try? It is for Hibernate 5 only.

**Comment by jameskleeh** [comment] 2016-10-28 14:18
This particular issue is fixed, however because of spring boot, you have to define the dependency of liquibase-core:

`compile 'org.liquibase:liquibase-core:3.5.3'`

In addition, it now wants to drop and re-add the index every time :trollface:

**Closed by jameskleeh** 2016-10-28 14:18 UTC
Labels: Awaiting Feedback, Bug

**Comment by markoschnecke** [comment] 2016-10-31 10:14
@jameskleeh yes I can confirm the behavior that you've described. As you wrote, liquibase is now writing changelogs that want to drop an re-add the index every time. Since you closed this issue, are you addressing the issue in another ticket?

**Comment by jameskleeh** [comment] 2016-10-31 12:39
@markoschnecke I'm 95% sure the issue lies in liquibase-hibernate. You can create an issue there
