### ISSUE TITLE
dbm-generate-gorm-changelog does not automatically create indexs

### ISSUE THREAD

**Issue by snimavat** [grails-plugins/grails-database-migration#82] opened 2016-08-04 18:21 UTC
So if i have specified indexes in my gorm mappings as explained [here](http://docs.grails.org/latest/guide/GORM.html#databaseIndices) 

And generate dbm-generate-gorm-changelog - it does not automatically create indexes.

**Comment by robertoschwald** [comment] 2016-09-10 09:16
duplicate of #74 ?

**Comment by jameskleeh** [comment] 2016-10-27 19:28
Duplicate

**Closed by jameskleeh** 2016-10-27 19:28 UTC
